# Generated by Django 3.0.7 on 2022-11-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_items', models.IntegerField(default=1, verbose_name='No. of Claimed Items')),
                ('claimed_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Quantity', 'Quantity')], default='Quantity', max_length=200, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=13, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('consumer_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('available_item', models.IntegerField(default=1)),
                ('purchased_item', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=65, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('purchase_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('price_per_item', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Selling Price for a Single Item', max_digits=65, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('buying_price_item', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Buying Price for a Single Item', max_digits=65, null=True)),
                ('total_buying_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('dated_order', models.DateTimeField(auto_now_add=True)),
                ('stock_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_out_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('dated', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
